#!/usr/bin/env python3
"""Print the initial LLM prompt the solve server builds for one SpreadsheetBench task.

The runner posts a user message to POST /solve; the solve server wraps it with its own
system prompt (solver guide + skill catalog) and appends a workbook summary, a
"workbook has been loaded" line and skill suggestions before the model sees any of it.
This script reproduces that exact first turn without calling a real model:

1. Starts the real solve server from a GRID-agent checkout, with the model factory
   replaced by a stub that ends the conversation on its first turn.
2. Drives it the way the runner does: create a solve context, upload the task's input
   workbook, build the prompt with the runner's own build_prompt, POST /solve.
3. Prints the system and user entries from the returned transcript.

Because both sides run their real code, the output tracks whatever branch of either
repo is checked out.

Usage:
    uv run scripts/print_prompt.py 01_01
    uv run scripts/print_prompt.py --dataset data/spreadsheetbench-v2-fork/Debugging 01_01
    uv run scripts/print_prompt.py 01_01 --json > prompt.json
    uv run scripts/print_prompt.py 01_01 --solve-server-url http://localhost:3123

Without --dataset the task id is looked up in every dataset.json under data/ (runs excluded).

The GRID-agent checkout defaults to ../GRID-agent (override with --grid-agent or GRID_AGENT_DIR).
"""

from __future__ import annotations

import argparse
import asyncio
import inspect
import json
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

import httpx

from sheetbench_runner.dataset import Dataset
from sheetbench_runner.entities import Task
from sheetbench_runner.prompt import build_prompt
from sheetbench_runner.solve_client import SolveClient
from sheetbench_runner.solve_profile import load_solve_profile

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
RUNS_DIR = DATA_DIR / "runs"
DEFAULT_PROFILE = REPO_ROOT / "profiles" / "anthropic-profile.json"
DEFAULT_PORT = 3123
SERVER_START_TIMEOUT_SECONDS = 120

# The solve server's entry point with the model factory swapped for a stub. Written into
# the gitignored .scratch/ directory of the solve-server app so its relative imports and
# workspace packages resolve exactly as they do for src/index.ts.
DRY_RUN_SERVER_TS = """\
// Generated by sheetbench-runner/scripts/print_prompt.py. Do not edit; do not commit.
import { serve } from '@hono/node-server';
import { Model } from '@grid-is/apiary';
import type { LlmClient, LlmEvent } from '@grid-is/grid-agent';
import { createApp } from '../src/app.ts';
import { SolveContextStore } from '../src/store/solve-context-store.ts';
import { WorkbookStore } from '../src/store/workbook-store.ts';

const PORT = parseInt(process.env.PORT ?? '3123', 10);

/** Answers every request with one short text turn, so the solve ends after the initial prompt. */
function stubLlm (): LlmClient {
  const events: LlmEvent[] = [
    { type: 'text_start' },
    { type: 'text_delta', text: '[dry run: no model was called]' },
    { type: 'text_end' },
    { type: 'usage', inputTokens: 0, outputTokens: 0 },
    { type: 'turn_end', stopReason: 'end_turn' },
  ];
  return {
    stream: () => ({
      controller: { abort () {} },
      async *[Symbol.asyncIterator] () {
        yield* events;
      },
    }),
  };
}

async function main (): Promise<void> {
  await Model.preconditions;
  const store = new WorkbookStore(undefined);
  const contexts = new SolveContextStore({
    onExpire: workbookIds => workbookIds.forEach(workbookId => store.clear(workbookId)),
  });
  const app = createApp({ store, contexts, createLlm: () => stubLlm() });
  serve({ fetch: app.fetch, port: PORT });
  console.error(`dry-run solve server listening on ${PORT}`);
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.stack ?? err.message : String(err));
  process.exit(1);
});
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("task_id", help="Task id, e.g. 09_01")
    parser.add_argument(
        "--dataset",
        type=Path,
        default=None,
        help="Dataset dir with dataset.json (default: the one under data/ holding the id)",
    )
    parser.add_argument(
        "--solve-profile",
        type=Path,
        default=DEFAULT_PROFILE,
        help="Solve profile JSON; only its model names matter (default: %(default)s)",
    )
    parser.add_argument(
        "--grid-agent",
        type=Path,
        default=Path(os.environ.get("GRID_AGENT_DIR", REPO_ROOT.parent / "GRID-agent")),
        help="GRID-agent checkout to start the dry-run solve server from (default: %(default)s)",
    )
    parser.add_argument(
        "--solve-server-url",
        default=None,
        help="Use an already running dry-run solve server instead of starting one",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help="Port for the spawned server (default: %(default)s)",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of delimited text")
    parser.add_argument(
        "--runner-only",
        action="store_true",
        help="Only print the message the runner would post; do not start or call a solve server",
    )
    return parser.parse_args(argv)


def find_task(dataset: Dataset, task_id: str) -> Task | None:
    return next((task for task in dataset.all_tasks if task.id == task_id), None)


def resolve_task(dataset_dir: Path | None, task_id: str) -> tuple[Dataset, Task]:
    """The dataset named on the command line, or the one dataset under data/ holding the id."""
    if dataset_dir is not None:
        dataset = Dataset(dataset_dir.resolve())
        task = find_task(dataset, task_id)
        if task is None:
            sys.exit(f"Task {task_id!r} not found in {dataset.dataset_path}")
        return dataset, task

    candidates = sorted(
        p.parent for p in DATA_DIR.rglob("dataset.json") if RUNS_DIR not in p.parents
    )
    matches = [(d, t) for d in map(Dataset, candidates) if (t := find_task(d, task_id))]
    if len(matches) == 1:
        return matches[0]
    if not matches:
        sys.exit(f"Task {task_id!r} is in no dataset under {DATA_DIR}; pass --dataset")
    names = ", ".join(str(d.dataset_path) for d, _ in matches)
    sys.exit(f"Task {task_id!r} is in several datasets, pass --dataset: {names}")


def runner_prompt(task: Task, workbook_id: str) -> str:
    """Call build_prompt with whichever signature the checked-out runner has.

    master takes (task, workbook_id); upstream-style-v2-prompt takes (task). One of the two
    calls is always a type error for mypy, which is why this script sits outside its target.
    """
    if "workbook_id" in inspect.signature(build_prompt).parameters:
        return build_prompt(task, workbook_id)
    return build_prompt(task)


class DryRunServer:
    """A solve server started from a GRID-agent checkout with a stub model."""

    def __init__(self, grid_agent: Path, port: int):
        self.app_dir = grid_agent / "apps" / "solve-server"
        self.port = port
        self.process: subprocess.Popen[bytes] | None = None
        self.stderr: tempfile.SpooledTemporaryFile[bytes] | None = None

    @property
    def url(self) -> str:
        return f"http://localhost:{self.port}"

    def __enter__(self) -> DryRunServer:
        tsx = self.app_dir.parent.parent / "node_modules" / ".bin" / "tsx"
        if not tsx.exists():
            sys.exit(f"tsx not found at {tsx}; is this a GRID-agent checkout with node_modules?")
        scratch = self.app_dir / ".scratch"
        scratch.mkdir(exist_ok=True)
        entry = scratch / "dry-run-server.ts"
        entry.write_text(DRY_RUN_SERVER_TS)
        # Logs go to a temp file rather than a pipe so a chatty server never blocks on it.
        self.stderr = tempfile.SpooledTemporaryFile(max_size=1 << 20)
        self.process = subprocess.Popen(
            [str(tsx), str(entry)],
            cwd=self.app_dir,
            env={**os.environ, "PORT": str(self.port)},
            stdout=subprocess.DEVNULL,
            stderr=self.stderr,
        )
        self._wait_until_ready()
        return self

    def __exit__(self, *exc: object) -> None:
        if self.process and self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()
        if self.stderr:
            self.stderr.close()

    def _read_stderr(self) -> str:
        if not self.stderr:
            return ""
        self.stderr.seek(0)
        return self.stderr.read().decode(errors="replace")

    def _wait_until_ready(self) -> None:
        assert self.process is not None
        deadline = time.monotonic() + SERVER_START_TIMEOUT_SECONDS
        while time.monotonic() < deadline:
            if self.process.poll() is not None:
                code = self.process.returncode
                sys.exit(f"dry-run solve server exited with {code}:\n{self._read_stderr()}")
            try:
                if httpx.get(f"{self.url}/status", timeout=2).status_code == 200:
                    return
            except httpx.HTTPError:
                pass
            time.sleep(0.5)
        self.__exit__()
        sys.exit(
            f"dry-run solve server did not answer on {self.url} in {SERVER_START_TIMEOUT_SECONDS}s"
        )


async def capture_prompt(
    url: str, profile_path: Path, input_path: Path, task: Task
) -> dict[str, Any]:
    profile = load_solve_profile(profile_path)
    api_keys = {name: "dry-run" for name in profile.configuration.models}
    async with SolveClient(url, timeout_seconds=600) as client:
        await client.create_solve_context(profile.configuration, api_keys)
        try:
            workbook_id = await client.upload_workbook(input_path)
            prompt = runner_prompt(task, workbook_id)
            response = await client.solve(workbook_id, prompt)
        finally:
            await client.delete_solve_context()

    entries = response.transcript.get("entries", [])
    by_role = {
        e["role"]: e.get("content", "") for e in entries if e.get("role") in ("system", "user")
    }
    if "system" not in by_role or "user" not in by_role:
        roles = [e.get("role") for e in entries]
        sys.exit(f"Transcript lacks system/user entries; roles seen: {roles}")
    return {
        "task_id": task.id,
        "workbook_id": workbook_id,
        "input_file": str(input_path),
        "runner_message": prompt,
        "system": by_role["system"],
        "user": by_role["user"],
    }


def print_text(result: dict[str, Any]) -> None:
    def section(title: str, body: str) -> None:
        print(f"\n{'=' * 20} {title} {'=' * 20}\n")
        print(body)

    print(f"task: {result['task_id']}    input: {result['input_file']}")
    if "workbook_id" in result:
        print(f"workbook_id: {result['workbook_id']}")
    section("RUNNER MESSAGE (posted to /solve)", result["runner_message"])
    if "system" in result:
        section("SYSTEM PROMPT (solve server)", result["system"])
        section("USER MESSAGE (solve server, as the model sees it)", result["user"])


def main(argv: list[str]) -> None:
    args = parse_args(argv)
    dataset, task = resolve_task(args.dataset, args.task_id)
    input_path = dataset.get_input_path(task)
    if not input_path.exists():
        sys.exit(f"Input workbook not found: {input_path}")

    if args.runner_only:
        result: dict[str, Any] = {
            "task_id": task.id,
            "input_file": str(input_path),
            "runner_message": runner_prompt(task, "<workbook_id>"),
        }
    elif args.solve_server_url:
        url = args.solve_server_url
        result = asyncio.run(capture_prompt(url, args.solve_profile, input_path, task))
    else:
        with DryRunServer(args.grid_agent.resolve(), args.port) as server:
            result = asyncio.run(capture_prompt(server.url, args.solve_profile, input_path, task))

    if args.json:
        json.dump(result, sys.stdout, indent=2, ensure_ascii=False)
        print()
    else:
        print_text(result)


if __name__ == "__main__":
    main(sys.argv[1:])
